# tasks/urls.py
from rest_framework import routers
from tasks import views  # Import the views file from the 'tasks' app

# Initialize a default router to handle the URLs
router = routers.DefaultRouter()
# Register the TaskView to handle URLs under the "tasks" endpoint
router.register(r'tasks', views.TaskView, basename='task')

# These are the URLs generated by the router
urlpatterns = router.urls
