# Generated by Django 5.2 on 2025-04-24 20:24

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    (tasks.models.TaskStatus["PENDING"], "Pending"),
                    (tasks.models.TaskStatus["COMPLETED"], "Completed"),
                ],
                default=tasks.models.TaskStatus["PENDING"],
                max_length=20,
                verbose_name="Task Status",
            ),
        ),
    ]
